### ISSUE TITLE
`from skorch import NeuralNetClassifier` raises

### ISSUE THREAD

**Issue by adrinjalali** [skorch-dev/skorch#1071]
Reproducer:

```sh
$ mmamba env create -n test python pytorch pytorch-cpu skorch

$ mmamba activate test 

$ python
Python 3.13.0 | packaged by conda-forge | (main, Oct  8 2024, 20:04:32) [GCC 13.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from skorch import NeuralNetClassifier
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    from skorch import NeuralNetClassifier
  File "/home/adrin/micromamba/envs/test/lib/python3.13/site-packages/skorch/__init__.py", line 10, in <module>
    from .classifier import NeuralNetClassifier
  File "/home/adrin/micromamba/envs/test/lib/python3.13/site-packages/skorch/classifier.py", line 54, in <module>
    class NeuralNetClassifier(NeuralNet, ClassifierMixin):
    ...<177 lines>...
            return self.predict_proba(X).argmax(axis=1)
  File "/home/adrin/micromamba/envs/test/lib/python3.13/site-packages/skorch/classifier.py", line 55, in NeuralNetClassifier
    __doc__ = get_neural_net_clf_doc(NeuralNet.__doc__)
  File "/home/adrin/micromamba/envs/test/lib/python3.13/site-packages/skorch/classifier.py", line 47, in get_neural_net_clf_doc
    start, end = pattern.search(doc).span()
                 ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'span'
```

Details of package versions:

```
  Package                 Version  Build                        Channel           Size
────────────────────────────────────────────────────────────────────────────────────────
  Install:
────────────────────────────────────────────────────────────────────────────────────────

  + _libgcc_mutex             0.1  conda_forge                  conda-forge     Cached
  + _openmp_mutex             4.5  2_gnu                        conda-forge     Cached
  + bzip2                   1.0.8  h4bc722e_7                   conda-forge     Cached
  + ca-certificates     2024.8.30  hbcca054_0                   conda-forge     Cached
  + colorama                0.4.6  pyhd8ed1ab_0                 conda-forge     Cached
  + cpython                3.13.0  py313hd8ed1ab_100            conda-forge       46kB
  + filelock               3.16.1  pyhd8ed1ab_0                 conda-forge     Cached
  + fsspec              2024.10.0  pyhff2d567_0                 conda-forge     Cached
  + gmp                     6.3.0  hac33072_2                   conda-forge     Cached
  + gmpy2                   2.1.5  py313h11186cd_2              conda-forge      212kB
  + jinja2                  3.1.4  pyhd8ed1ab_0                 conda-forge     Cached
  + joblib                  1.4.2  pyhd8ed1ab_0                 conda-forge     Cached
  + ld_impl_linux-64         2.43  h712a8e2_2                   conda-forge     Cached
  + libabseil          20240722.0  cxx17_h5888daf_1             conda-forge     Cached
  + libblas                 3.9.0  25_linux64_openblas          conda-forge     Cached
  + libcblas                3.9.0  25_linux64_openblas          conda-forge     Cached
  + libexpat                2.6.3  h5888daf_0                   conda-forge     Cached
  + libffi                  3.4.2  h7f98852_5                   conda-forge     Cached
  + libgcc                 14.2.0  h77fa898_1                   conda-forge     Cached
  + libgcc-ng              14.2.0  h69a702a_1                   conda-forge     Cached
  + libgfortran            14.2.0  h69a702a_1                   conda-forge     Cached
  + libgfortran-ng         14.2.0  h69a702a_1                   conda-forge     Cached
  + libgfortran5           14.2.0  hd5240d6_1                   conda-forge     Cached
  + libgomp                14.2.0  h77fa898_1                   conda-forge     Cached
  + liblapack               3.9.0  25_linux64_openblas          conda-forge     Cached
  + libmpdec                4.0.0  h4bc722e_0                   conda-forge       90kB
  + libopenblas            0.3.28  pthreads_h94d23a6_0          conda-forge     Cached
  + libprotobuf            5.27.5  h5b01275_2                   conda-forge     Cached
  + libsqlite              3.47.0  hadc24fc_0                   conda-forge     Cached
  + libstdcxx              14.2.0  hc0a3c3a_1                   conda-forge     Cached
  + libstdcxx-ng           14.2.0  h4852527_1                   conda-forge     Cached
  + libtorch                2.4.1  cpu_generic_hca457ed_2       conda-forge       52MB
  + libuuid                2.38.1  h0b41bf4_0                   conda-forge     Cached
  + libuv                  1.49.2  hb9d3cd8_0                   conda-forge     Cached
  + libzlib                 1.3.1  hb9d3cd8_2                   conda-forge     Cached
  + markupsafe              3.0.2  py313h8060acc_0              conda-forge       25kB
  + mpc                     1.3.1  h24ddda3_1                   conda-forge     Cached
  + mpfr                    4.2.1  h90cbb55_3                   conda-forge     Cached
  + mpmath                  1.3.0  pyhd8ed1ab_0                 conda-forge     Cached
  + ncurses                   6.5  he02047a_1                   conda-forge     Cached
  + networkx                3.4.2  pyhd8ed1ab_0                 conda-forge     Cached
  + nomkl                     1.0  h5ca1d4c_0                   conda-forge     Cached
  + numpy                   2.1.2  py313h4bf6692_0              conda-forge        8MB
  + openssl                 3.3.2  hb9d3cd8_0                   conda-forge     Cached
  + pip                      24.2  pyh145f28c_1                 conda-forge        1MB
  + python                 3.13.0  h9ebbce0_100_cp313           conda-forge       33MB
  + python_abi               3.13  5_cp313                      conda-forge        6kB
  + pytorch                 2.4.1  cpu_generic_py313h30720f7_2  conda-forge       26MB
  + pytorch-cpu             2.4.1  cpu_generic_py313h7a53447_2  conda-forge       24kB
  + readline                  8.2  h8228510_1                   conda-forge     Cached
  + scikit-learn            1.5.2  py313h8ef605b_1              conda-forge       10MB
  + scipy                  1.14.1  py313h27c5614_1              conda-forge       18MB
  + setuptools             75.1.0  pyhd8ed1ab_0                 conda-forge     Cached
  + skorch                  1.0.0  pyhecae5ae_0                 conda-forge     Cached
  + sleef                     3.7  h1b44611_0                   conda-forge     Cached
  + sympy                  1.13.3  pyh2585a3b_104               conda-forge        5MB
  + tabulate                0.9.0  pyhd8ed1ab_1                 conda-forge     Cached
  + threadpoolctl           3.5.0  pyhc1e730c_0                 conda-forge     Cached
  + tk                     8.6.13  noxft_h4845f30_101           conda-forge     Cached
  + tqdm                   4.66.5  pyhd8ed1ab_0                 conda-forge       90kB
  + typing_extensions      4.12.2  pyha770c72_0                 conda-forge     Cached
  + tzdata                  2024b  hc8b5060_0                   conda-forge     Cached
  + xz                      5.2.6  h166bdaf_0                   conda-forge     Cached
```

**Comment by adrinjalali** [comment]
Note that this will make the _test_ pass:

```sh
$ mmamba env create -n test python "pytorch<2.4" "pytorch-cpu<2.4" skorch   
```

**Comment by BenjaminBossan** [comment]
Thanks for reporting. I'm not sure what `mmamba` is exactly, is it just `mamba` or something else?

I tried to replicate with a normal Python environment but was not successful. This part of the code is really innocuous so I'm not sure what would cause this to suddenly fail, really it would mean that there is a new behavior in `re`.

> Note that this will make the _test_ pass:
> 
> ```shell
> $ mmamba env create -n test python "pytorch<2.4" "pytorch-cpu<2.4" skorch  
> ```

Does that change the Python version for you? The first env has Python 3.13, which is not officially supported by skorch. But even so, I would be really surprised if this regex worked differently in Python 3.13 and I also tested it with 3.13 and it worked.

**Comment by adrinjalali** [comment]
Sorry, `mmamba` is an alias for `micromamba` for me. So nothing special.

> Does that change the Python version for you?

Yes, it makes it 3.12.7

So `mmamba env create -n test "python<3.13" "pytorch" "pytorch-cpu" skorch` also makes a usable environment, cause it gets `pytorch=2.4.1`

**Comment by BenjaminBossan** [comment]
Thanks for checking. So that makes it more likely that Python 3.13 is the issue, even though as mentioned, I could not reproduce it (using conda). As Python 3.13 is not officially supported yet, I think there is no immediate todo here, but let's keep the issue open.

As to why 3.13 is installed, this is probably because there is no mechanism to check for the max Python version, right? For your use case, can you add `python<3.13` to the env or if it's a CI, skip the skorch tests when Python >= 3.13 is detected?

**Comment by adrinjalali** [comment]
Which channels are you using? I'm using only `conda-forge`, not `pytorch` or `defaults`. At least on `conda-forge` `pytorch=2.5` seems to be compatible with `python=3.13`

**Comment by adrinjalali** [comment]
Ok, scratch that. I don't know where I got the 2.5 in my mind. Been doing too many CI fixes today.

So the issue seems the python, version which is very odd, but also as you say expected since torch doesn't support 3.13 yet. Sorry for the confusion. I'll close this issue then, hopefully when they release support for 3.13, this issue doesn't come up.
