### ISSUE TITLE
Cannot Gridsearch with CNN

### ISSUE THREAD

**Issue by jakobbrown** [skorch-dev/skorch#745]
Hi, i am running a NeuralNetClassifier object no problem for a CNN, but when i try to run the same thing as a GridSearch i am getting an 'estimator fit failed' error:

```
class cnn(nn.Module):
    def __init__(self, 
                dropout = dropout,
                conv1 = conv1, 
                conv2 = conv2,
                conv3 = conv3,
                dense1 = dense1,
                dense2 = dense2,
                stride1 = stride1,
                padding1 = padding1,
                stride2 = stride2,
                padding2 = padding2):
        super(cnn, self).__init__()
        self.network = nn.Sequential(
            
            nn.Conv2d(3, conv1, kernel_size=3, padding=padding1),
            nn.BatchNorm2d(conv1),
            nn.ReLU(inplace = True),
            nn.Conv2d(conv1, conv2, kernel_size=3, stride=stride2, padding=padding2),
            nn.ReLU(inplace = True),
            nn.MaxPool2d(2, 2), # output: 64 x 16 x 16: 

            nn.Flatten(), 
            nn.Linear(conv2*16*16, dense1),
            nn.ReLU(inplace = True),
            nn.Dropout(dropout),
            nn.Linear(dense1, dense2),
            nn.ReLU(inplace = True),
            nn.Linear(dense2, 10))
        
    def forward(self, i):
        return self.network(i)
```

```
from skorch import NeuralNetClassifier

earlystopping = skorch.callbacks.EarlyStopping(monitor = 'valid_acc', lower_is_better = False,
                                               patience = 3, threshold_mode = 'abs')

checkpoint = skorch.callbacks.Checkpoint(monitor = 'valid_acc_best')

# defining the classifier object


cnnskorch = NeuralNetClassifier(
        cnn,
        criterion = nn.CrossEntropyLoss,
        optimizer = torch.optim.Adam,
        batch_size = 64,
        max_epochs = 15,
        lr = lr,
        callbacks = [earlystopping, checkpoint]
        )
```

```
# Specifying parameters to be searched through

params = {'module__conv1': [16, 32],
          'module__conv2': [64, 128],
          
          'module__dense1': [1000, 500],
          'module__dense2': [500, 250],
          
          #'module__stride2': [1, 2],
          

          'optimizer': [torch.optim.SGD, torch.optim.Adam],
          
          }
```

```
cnn_gs = GridSearchCV(cnnskorch, params, verbose = 2, cv = 2, scoring = 'accuracy')

cnn_gs.fit(xTrain, yTrain)
```

To clarify, fitting cnnskorch to xTrain and yTrain works fine, but fitting cnn_gs does not, nor does cnn_gs.fit(data, yTrain) Any advice on this? i thought it may have something to do with the gridsearch parameters changing the dimensionality of the input and thus yielding an error between convolutional layers, but i'm fairly sure this isn't the case. i recently used the same process for an MLP and that worked perfect, so perhaps i am making a mistake due to some CNN naïveté?

The data i am using is just the torchvision.datasets.CIFAR10, thus starting at 32x32x3 dimensionality, if that is relevant. yTrain is converted to an np.array.

hyperparameters are:

```
conv1 = 32
conv2 = 64
conv3 = 128

dense1 = 1024
dense2 = 512

padding1 = 1
stride1 = 1

padding2 = 1
stride2 = 1
```

**Comment by BenjaminBossan** [comment]
Most likely, one of the hyper-parameter combinations causes the error, but I can't spot it right now. Could you please paste everything that is printed when you're fitting the grid search?

**Comment by jakobbrown** [comment]
Sure thing:

if i do cnn_gs.fit(xTrain, yTrain), the error looks like this:

```
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
/Applications/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 531, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/classifier.py", line 142, in fit
    return super(NeuralNetClassifier, self).fit(X, y, **fit_params)
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/net.py", line 903, in fit
    self.partial_fit(X, y, **fit_params)
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/net.py", line 862, in partial_fit
    self.fit_loop(X, y, **fit_params)
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/net.py", line 765, in fit_loop
    dataset_train, dataset_valid = self.get_split_datasets(
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/net.py", line 1292, in get_split_datasets
    dataset = self.get_dataset(X, y)
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/net.py", line 1247, in get_dataset
    return dataset(X, y, **kwargs)
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/dataset.py", line 169, in __init__
    raise ValueError("X and y have inconsistent lengths.")
ValueError: X and y have inconsistent lengths.

  warnings.warn("Estimator fit failed. The score on this train-test"
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:   13.1s remaining:    0.0s
[CV]  module__conv1=16, module__conv2=64, module__dense1=1000, module__dense2=500, optimizer=<class 'torch.optim.sgd.SGD'>, total=  12.8s
[CV] module__conv1=16, module__conv2=64, module__dense1=1000, module__dense2=500, optimizer=<class 'torch.optim.sgd.SGD'> 
[CV]  module__conv1=16, module__conv2=64, module__dense1=1000, module__dense2=500, optimizer=<class 'torch.optim.sgd.SGD'>, total=   8.8s
[CV] module__conv1=16, module__conv2=64, module__dense1=1000, module__dense2=500, optimizer=<class 'torch.optim.adam.Adam'> 
[CV]  module__conv1=16, module__conv2=64, module__dense1=1000, module__dense2=500, optimizer=<class 'torch.optim.adam.Adam'>, total=   8.2s
[CV] module__conv1=16, module__conv2=64, module__dense1=1000, module__dense2=500, optimizer=<class 'torch.optim.adam.Adam'> 
[CV]  module__conv1=16, module__conv2=64, module__dense1=1000, module__dense2=500, optimizer=<class 'torch.optim.adam.Adam'>, total=   9.4s
[CV] module__conv1=16, module__conv2=64, module__dense1=1000, module__dense2=250, optimizer=<class 'torch.optim.sgd.SGD'> 
[CV]  module__conv1=16, module__conv2=64, module__dense1=1000, module__dense2=250, optimizer=<class 'torch.optim.sgd.SGD'>, total=  11.3s
[CV] module__conv1=16, module__conv2=64, module__dense1=1000, module__dense2=250, optimizer=<class 'torch.optim.sgd.SGD'> 
[CV]  module__conv1=16, module__conv2=64, module__dense1=1000, module__dense2=250, optimizer=<class 'torch.optim.sgd.SGD'>, total=  10.0s
[CV] module__conv1=16, module__conv2=64, module__dense1=1000, module__dense2=250, optimizer=<class 'torch.optim.adam.Adam'> 
[CV]  module__conv1=16, module__conv2=64, module__dense1=1000, module__dense2=250, optimizer=<class 'torch.optim.adam.Adam'>, total=   8.3s
[CV] module__conv1=16, module__conv2=64, module__dense1=1000, module__dense2=250, optimizer=<class 'torch.optim.adam.Adam'> 
[CV]  module__conv1=16, module__conv2=64, module__dense1=1000, module__dense2=250, optimizer=<class 'torch.optim.adam.Adam'>, total=   8.2s
[CV] module__conv1=16, module__conv2=64, module__dense1=500, module__dense2=500, optimizer=<class 'torch.optim.sgd.SGD'> 
[CV]  module__conv1=16, module__conv2=64, module__dense1=500, module__dense2=500, optimizer=<class 'torch.optim.sgd.SGD'>, total=   8.5s
[CV] module__conv1=16, module__conv2=64, module__dense1=500, module__dense2=500, optimizer=<class 'torch.optim.sgd.SGD'> 
[CV]  module__conv1=16, module__conv2=64, module__dense1=500, module__dense2=500, optimizer=<class 'torch.optim.sgd.SGD'>, total=  10.4s
[CV] module__conv1=16, module__conv2=64, module__dense1=500, module__dense2=500, optimizer=<class 'torch.optim.adam.Adam'> 
[CV]  module__conv1=16, module__conv2=64, module__dense1=500, module__dense2=500, optimizer=<class 'torch.optim.adam.Adam'>, total=   8.8s
[CV] module__conv1=16, module__conv2=64, module__dense1=500, module__dense2=500, optimizer=<class 'torch.optim.adam.Adam'> 
[CV]  module__conv1=16, module__conv2=64, module__dense1=500, module__dense2=500, optimizer=<class 'torch.optim.adam.Adam'>, total=   9.9s
```

The list of hyperparameter combinations keeps on going, i've just cut it off here, it seems to be for every combination.

I then try cnn_gs.fit(data, yTrain) and i get a different error:

```
Fitting 2 folds for each of 32 candidates, totalling 64 fits
[CV] module__conv1=16, module__conv2=64, module__dense1=1000, module__dense2=500, optimizer=<class 'torch.optim.sgd.SGD'> 
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
/Applications/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 531, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/classifier.py", line 142, in fit
    return super(NeuralNetClassifier, self).fit(X, y, **fit_params)
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/net.py", line 903, in fit
    self.partial_fit(X, y, **fit_params)
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/net.py", line 862, in partial_fit
    self.fit_loop(X, y, **fit_params)
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/net.py", line 775, in fit_loop
    self.run_single_epoch(dataset_train, training=True, prefix="train",
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/net.py", line 812, in run_single_epoch
    step = step_fn(Xi, yi, **fit_params)
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/net.py", line 709, in train_step
    self.optimizer_.step(step_fn)
  File "/Applications/anaconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/Applications/anaconda3/lib/python3.8/site-packages/torch/optim/sgd.py", line 86, in step
    loss = closure()
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/net.py", line 705, in step_fn
    step = self.train_step_single(Xi, yi, **fit_params)
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/net.py", line 645, in train_step_single
    y_pred = self.infer(Xi, **fit_params)
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/net.py", line 1048, in infer
    return self.module_(x, **fit_params)
  File "/Applications/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "<ipython-input-68-bc2ce8df9b14>", line 48, in forward
    return self.network(i)
  File "/Applications/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Applications/anaconda3/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/Applications/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Applications/anaconda3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "/Applications/anaconda3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 419, in _conv_forward
    return F.conv2d(input, weight, self.bias, self.stride,
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [16, 3, 3, 3], but got 2-dimensional input of size [64, 3072] instead

  warnings.warn("Estimator fit failed. The score on this train-test"
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    1.3s remaining:    0.0s
[CV]  module__conv1=16, module__conv2=64, module__dense1=1000, module__dense2=500, optimizer=<class 'torch.optim.sgd.SGD'>, total=   1.1s
[CV] module__conv1=16, module__conv2=64, module__dense1=1000, module__dense2=500, optimizer=<class 'torch.optim.sgd.SGD'> 
/Applications/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 531, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/classifier.py", line 142, in fit
    return super(NeuralNetClassifier, self).fit(X, y, **fit_params)
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/net.py", line 903, in fit
    self.partial_fit(X, y, **fit_params)
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/net.py", line 862, in partial_fit
    self.fit_loop(X, y, **fit_params)
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/net.py", line 775, in fit_loop
    self.run_single_epoch(dataset_train, training=True, prefix="train",
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/net.py", line 812, in run_single_epoch
    step = step_fn(Xi, yi, **fit_params)
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/net.py", line 709, in train_step
    self.optimizer_.step(step_fn)
  File "/Applications/anaconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/Applications/anaconda3/lib/python3.8/site-packages/torch/optim/sgd.py", line 86, in step
    loss = closure()
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/net.py", line 705, in step_fn
    step = self.train_step_single(Xi, yi, **fit_params)
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/net.py", line 645, in train_step_single
    y_pred = self.infer(Xi, **fit_params)
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/net.py", line 1048, in infer
    return self.module_(x, **fit_params)
  File "/Applications/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "<ipython-input-68-bc2ce8df9b14>", line 48, in forward
    return self.network(i)
  File "/Applications/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Applications/anaconda3/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/Applications/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Applications/anaconda3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "/Applications/anaconda3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 419, in _conv_forward
    return F.conv2d(input, weight, self.bias, self.stride,
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [16, 3, 3, 3], but got 2-dimensional input of size [64, 3072] instead

  warnings.warn("Estimator fit failed. The score on this train-test"
[CV]  module__conv1=16, module__conv2=64, module__dense1=1000, module__dense2=500, optimizer=<class 'torch.optim.sgd.SGD'>, total=   0.4s
[CV] module__conv1=16, module__conv2=64, module__dense1=1000, module__dense2=500, optimizer=<class 'torch.optim.adam.Adam'> 
/Applications/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 531, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/classifier.py", line 142, in fit
    return super(NeuralNetClassifier, self).fit(X, y, **fit_params)
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/net.py", line 903, in fit
    self.partial_fit(X, y, **fit_params)
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/net.py", line 862, in partial_fit
    self.fit_loop(X, y, **fit_params)
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/net.py", line 775, in fit_loop
    self.run_single_epoch(dataset_train, training=True, prefix="train",
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/net.py", line 812, in run_single_epoch
    step = step_fn(Xi, yi, **fit_params)
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/net.py", line 709, in train_step
    self.optimizer_.step(step_fn)
  File "/Applications/anaconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/Applications/anaconda3/lib/python3.8/site-packages/torch/optim/adam.py", line 66, in step
    loss = closure()
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/net.py", line 705, in step_fn
    step = self.train_step_single(Xi, yi, **fit_params)
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/net.py", line 645, in train_step_single
    y_pred = self.infer(Xi, **fit_params)
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/net.py", line 1048, in infer
    return self.module_(x, **fit_params)
  File "/Applications/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "<ipython-input-68-bc2ce8df9b14>", line 48, in forward
    return self.network(i)
  File "/Applications/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Applications/anaconda3/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/Applications/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Applications/anaconda3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "/Applications/anaconda3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 419, in _conv_forward
    return F.conv2d(input, weight, self.bias, self.stride,
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [16, 3, 3, 3], but got 2-dimensional input of size [64, 3072] instead

  warnings.warn("Estimator fit failed. The score on this train-test"
[CV]  module__conv1=16, module__conv2=64, module__dense1=1000, module__dense2=500, optimizer=<class 'torch.optim.adam.Adam'>, total=   0.4s
[CV] module__conv1=16, module__conv2=64, module__dense1=1000, module__dense2=500, optimizer=<class 'torch.optim.adam.Adam'> 
/Applications/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 531, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/classifier.py", line 142, in fit
    return super(NeuralNetClassifier, self).fit(X, y, **fit_params)
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/net.py", line 903, in fit
    self.partial_fit(X, y, **fit_params)
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/net.py", line 862, in partial_fit
    self.fit_loop(X, y, **fit_params)
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/net.py", line 775, in fit_loop
    self.run_single_epoch(dataset_train, training=True, prefix="train",
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/net.py", line 812, in run_single_epoch
    step = step_fn(Xi, yi, **fit_params)
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/net.py", line 709, in train_step
    self.optimizer_.step(step_fn)
  File "/Applications/anaconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/Applications/anaconda3/lib/python3.8/site-packages/torch/optim/adam.py", line 66, in step
    loss = closure()
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/net.py", line 705, in step_fn
    step = self.train_step_single(Xi, yi, **fit_params)
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/net.py", line 645, in train_step_single
    y_pred = self.infer(Xi, **fit_params)
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/net.py", line 1048, in infer
    return self.module_(x, **fit_params)
  File "/Applications/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "<ipython-input-68-bc2ce8df9b14>", line 48, in forward
    return self.network(i)
  File "/Applications/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Applications/anaconda3/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/Applications/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Applications/anaconda3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "/Applications/anaconda3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 419, in _conv_forward
    return F.conv2d(input, weight, self.bias, self.stride,
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [16, 3, 3, 3], but got 2-dimensional input of size [64, 3072] instead

  warnings.warn("Estimator fit failed. The score on this train-test"
[CV]  module__conv1=16, module__conv2=64, module__dense1=1000, module__dense2=500, optimizer=<class 'torch.optim.adam.Adam'>, total=   0.4s
[CV] module__conv1=16, module__conv2=64, module__dense1=1000, module__dense2=250, optimizer=<class 'torch.optim.sgd.SGD'> 
/Applications/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 531, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/classifier.py", line 142, in fit
    return super(NeuralNetClassifier, self).fit(X, y, **fit_params)
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/net.py", line 903, in fit
    self.partial_fit(X, y, **fit_params)
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/net.py", line 862, in partial_fit
    self.fit_loop(X, y, **fit_params)
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/net.py", line 775, in fit_loop
    self.run_single_epoch(dataset_train, training=True, prefix="train",
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/net.py", line 812, in run_single_epoch
    step = step_fn(Xi, yi, **fit_params)
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/net.py", line 709, in train_step
    self.optimizer_.step(step_fn)
  File "/Applications/anaconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/Applications/anaconda3/lib/python3.8/site-packages/torch/optim/sgd.py", line 86, in step
    loss = closure()
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/net.py", line 705, in step_fn
    step = self.train_step_single(Xi, yi, **fit_params)
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/net.py", line 645, in train_step_single
    y_pred = self.infer(Xi, **fit_params)
  File "/Applications/anaconda3/lib/python3.8/site-packages/skorch/net.py", line 1048, in infer
    return self.module_(x, **fit_params)
  File "/Applications/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "<ipython-input-68-bc2ce8df9b14>", line 48, in forward
    return self.network(i)
  File "/Applications/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Applications/anaconda3/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/Applications/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Applications/anaconda3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "/Applications/anaconda3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 419, in _conv_forward
    return F.conv2d(input, weight, self.bias, self.stride,
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [16, 3, 3, 3], but got 2-dimensional input of size [64, 3072] instead

  warnings.warn("Estimator fit failed. The score on this train-test"
[CV]  module__conv1=16, module__conv2=64, module__dense1=1000, module__dense2=250, optimizer=<class 'torch.optim.sgd.SGD'>, total=   0.4s
[CV] module__conv1=16, module__conv2=64, module__dense1=1000, module__dense2=250, optimizer=<class 'torch.optim.sgd.SGD'> 
```


This also is cut short by me, as it just repeats itself, but there are no combinations of hyperparameters that don't generate the same error.

**Comment by BenjaminBossan** [comment]
Okay, this is not about the hyper-parameters. Instead, it seems to be about the data itself. What is the type of `data` and `xTrain`? If they are datasets, please take a look at [this suggestion](https://skorch.readthedocs.io/en/stable/user/FAQ.html?highlight=slicedataset#how-do-i-use-sklearn-gridseachcv-when-my-data-is-in-a-dataset).

**Comment by jakobbrown** [comment]
Success! xTrain is actually an numpy nd.array so i thought that would work but it didn't

Data is indeed a torchvision.datasets object.

```
xTrain = data.data
xTrain = np.reshape(xTrain,(50000,3072))
xTrain = xTrain.astype('float32')

xTrain_2 = skorch.helper.SliceDataset(data, idx = 0)
yTrain_2 = skorch.helper.SliceDataset(data, idx = 1)
yTrain = np.array([y for x, y in iter(data.targets)])
```

To clarify, the one that worked for me was cnn_gs.fit(xTrain_2, yTrain)

using data, xTrain, and even cnn_gs.fit(xTrain_2, yTrain_2) did not work. 

Thanks a lot for your help and quick response Benjamin .

**Comment by BenjaminBossan** [comment]
@jakobbrown glad that this solved the problem.

Just a tip: When you use grid search, you might want to turn down the verbosity of skorch by setting `cnnskorch = NeuralNetClassifier(..., verbose=0)`; otherwise, you will be flooded with logs coming from both skorch and sklearn.
