### ISSUE TITLE
TypeError: 'NeuralNet' object is not callable [solved] and KeyError: "Key 'valid_loss' was not found in history."

### ISSUE THREAD

**Issue by Zepp3** [skorch-dev/skorch#746]
Hi,
I want to implement a GAN with skorch, as this would be a really simple way of hyperparameter tuning concerning GANs.
I got the following error, and don't know how to handle it:
```
C:\Users\Josef\anaconda3\envs\pythonProject\python.exe C:\Users\Josef\PycharmProjects\GANs\GANFromScratch_Hyperparameters.py
Traceback (most recent call last):
  File "C:\Users\Josef\PycharmProjects\GANs\GANFromScratch_Hyperparameters.py", line 207, in <module>
    fake_data = generator(noise(N)).detach()
TypeError: 'NeuralNet' object is not callable

Process finished with exit code 1
```

My code is:
```python
from torch import nn, optim
from torchvision import transforms, datasets
import torch
from skorch import NeuralNet
from skorch import callbacks
from sklearn.model_selection import RandomizedSearchCV


DATA_FOLDER = './torch_data/VGAN/MNIST'


def mnist_data():
    compose = transforms.Compose([
        transforms.ToTensor(), transforms.Normalize([0.5], [0.5])])
    out_dir = 'C:\\Users\\Josef\\PycharmProjects\\GANs\\dataset'
    return datasets.MNIST(root=out_dir, train=True, transform=compose, download=False)
# Load data
data = mnist_data()
# Create loader with data, so that we can iterate over it
data_loader = torch.utils.data.DataLoader(data, batch_size=2, shuffle=False)
# Num batches
num_batches = len(data_loader)


def images_to_vectors(images):
    return images.view(images.size(0), 784)

def vectors_to_images(vectors):
    return vectors.view(vectors.size(0), 1, 28, 28)


class DiscriminatorNet(torch.nn.Module):
    """
    A three hidden-layer discriminative neural network
    """

    def __init__(self, dropout=.5):
        super(DiscriminatorNet, self).__init__()
        n_features = 784
        n_out = 1

        self.hidden0 = nn.Sequential(
            nn.Linear(n_features, 1024),
            nn.LeakyReLU(0.2),
            nn.Dropout(0.3)
        )
        self.hidden1 = nn.Sequential(
            nn.Linear(1024, 512),
            nn.LeakyReLU(0.2),
            nn.Dropout(0.3)
        )
        self.hidden2 = nn.Sequential(
            nn.Linear(512, 256),
            nn.LeakyReLU(0.2),
            nn.Dropout(0.3)
        )
        self.out = nn.Sequential(
            torch.nn.Linear(256, n_out),
            torch.nn.Sigmoid()
        )

    def forward(self, x):
        x = self.hidden0(x)
        x = self.hidden1(x)
        x = self.hidden2(x)
        x = self.out(x)
        return x

discriminator = DiscriminatorNet()
discriminator.to("cuda:0")

discriminator = NeuralNet(
    module=DiscriminatorNet,
    callbacks=[callbacks.EarlyStopping(patience=10)],
    criterion=torch.nn.MSELoss,
    optimizer=torch.optim.SGD,
    max_epochs=0,
    lr=0.00001,
    batch_size=2,
    iterator_train__shuffle=False,
    verbose=0,
    device="cuda:0",
    train_split=None)



class GeneratorNet(torch.nn.Module):
    """
    A three hidden-layer generative neural network
    """

    def __init__(self, dropout=.5):
        super(GeneratorNet, self).__init__()
        n_features = 100
        n_out = 784

        self.hidden0 = nn.Sequential(
            nn.Linear(n_features, 256),
            nn.LeakyReLU(0.2)
        )
        self.hidden1 = nn.Sequential(
            nn.Linear(256, 512),
            nn.LeakyReLU(0.2)
        )
        self.hidden2 = nn.Sequential(
            nn.Linear(512, 1024),
            nn.LeakyReLU(0.2)
        )

        self.out = nn.Sequential(
            nn.Linear(1024, n_out),
            nn.Tanh()
        )

    def forward(self, x):
        x = self.hidden0(x)
        x = self.hidden1(x)
        x = self.hidden2(x)
        x = self.out(x)
        return x

generator = GeneratorNet()
generator.to("cuda:0")

generator = NeuralNet(
    module=GeneratorNet,
    callbacks=[callbacks.EarlyStopping(patience=10)],
    criterion=torch.nn.MSELoss,
    optimizer=torch.optim.SGD,
    max_epochs=0,
    lr=0.00001,
    batch_size=2,
    iterator_train__shuffle=False,
    verbose=0,
    device="cuda:0",
    train_split=None)


def noise(size):
    '''
    Generates a 1-d vector of gaussian sampled random values
    '''
    n = torch.randn(size, 100, device='cuda:0')
    return n


def ones_target(size):
    '''
    Tensor containing ones, with shape = size
    '''
    data = torch.ones(size, 1)
    data = data.to("cuda:0")
    return data

def zeros_target(size):
    '''
    Tensor containing zeros, with shape = size
    '''
    data = torch.zeros(size, 1)
    data = data.to("cuda:0")
    return data


def train_discriminator(real_data, fake_data):
    params_discriminator = {
        'max_epochs': [750],
        'lr': [0.000001],
        'batch_size': [2],
        'module__dropout': [.1]}

    # 1.1 Train on Real Data
    train_discriminator = RandomizedSearchCV(discriminator, params_discriminator, cv=2, scoring="neg_mean_squared_error",
                                         verbose=100,
                                         n_jobs=-1)
    train_discriminator.fit(real_data, ones_target(N))

    # 1.2 Train on Fake Data
    train_discriminator = RandomizedSearchCV(discriminator, params_discriminator, cv=2,
                                             scoring="neg_mean_squared_error",
                                             verbose=100,
                                             n_jobs=-1)
    train_discriminator.fit(fake_data, zeros_target(N))


def train_generator(fake_data):
    params_generator = {
        'max_epochs': [750],
        'lr': [0.000001],
        'batch_size': [2],
        'module__dropout': [.1]}

    train_generator = RandomizedSearchCV(generator, params_generator, cv=2, scoring="neg_mean_squared_error", verbose=100,
                                         n_jobs=-1)

    train_generator.fit(fake_data, ones_target(N))


# Total number of epochs to train
num_epochs = 200
for epoch in range(num_epochs):
    for real_batch, _ in data_loader:
        real_batch = real_batch.to('cuda:0')
        N = real_batch.size(0)
        # 1. Train Discriminator
        real_data = images_to_vectors(real_batch)
        # Generate fake data and detach (so gradients are not calculated for generator)
        fake_data = generator(noise(N)).detach()
        # Train D
        train_discriminator(real_data, fake_data)

        # 2. Train Generator
        # Generate fake data
        fake_data = generator(noise(N))
        # Train generator
        train_generator(fake_data)
```

Is the problem that the NeuralNet object of skorch is in general not callable?
Thanks in advance!

**Comment by ottonemo** [comment]
> Is the problem that the NeuralNet object of skorch is in general not callable?

Yes, that is exactly the problem. You can use `generator.forward` or `generator.forward_iter` instead which should do the job (the same for the discriminator). This is by design as we don't want to give the impression that `NeuralNet` objects can simply be chained together. There is a multitude of APIs (torch-style `forward` and sklearn-style `predict` comes to mind) so the user should be able to chose (e.g., by subclassing) instead of being forced into a default.

This looks very interesting, if you have results, feel free to share them :)

**Comment by Zepp3** [comment]
Hi @ottonemo,
thanks! That solved the problem.
I'm glad to hear that you are interested and I'd love to share my results as soon as I got some but for the moment I'm still struggling...
Right now I got the following output:
```
C:\Users\Josef\anaconda3\envs\pythonProject\python.exe C:\Users\Josef\PycharmProjects\GANs\GANFromScratch_Hyperparameters.py
Fitting 2 folds for each of 1 candidates, totalling 2 fits
[CV 1/2; 1/1] START batch_size=2, lr=1e-06, max_epochs=750, module__dropout=0.1.
[CV 2/2; 1/1] START batch_size=2, lr=1e-06, max_epochs=750, module__dropout=0.1.
[CV 1/2; 1/1] END batch_size=2, lr=1e-06, max_epochs=750, module__dropout=0.1; total time=   1.5s
C:\Users\Josef\anaconda3\envs\pythonProject\lib\site-packages\sklearn\model_selection\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\Josef\anaconda3\envs\pythonProject\lib\site-packages\sklearn\model_selection\_validation.py", line 593, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Josef\anaconda3\envs\pythonProject\lib\site-packages\skorch\net.py", line 917, in fit
    self.partial_fit(X, y, **fit_params)
  File "C:\Users\Josef\anaconda3\envs\pythonProject\lib\site-packages\skorch\net.py", line 876, in partial_fit
    self.fit_loop(X, y, **fit_params)
  File "C:\Users\Josef\anaconda3\envs\pythonProject\lib\site-packages\skorch\net.py", line 796, in fit_loop
    self.notify("on_epoch_end", **on_epoch_kwargs)
  File "C:\Users\Josef\anaconda3\envs\pythonProject\lib\site-packages\skorch\net.py", line 334, in notify
    getattr(cb, method_name)(self, **cb_kwargs)
  File "C:\Users\Josef\anaconda3\envs\pythonProject\lib\site-packages\skorch\callbacks\training.py", line 377, in on_epoch_end
    current_score = net.history[-1, self.monitor]
  File "C:\Users\Josef\anaconda3\envs\pythonProject\lib\site-packages\skorch\history.py", line 310, in __getitem__
    raise KeyError(keyerror_msg.format(k_e))
KeyError: "Key 'valid_loss' was not found in history."

  warnings.warn("Estimator fit failed. The score on this train-test"
C:\Users\Josef\anaconda3\envs\pythonProject\lib\site-packages\sklearn\model_selection\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\Josef\anaconda3\envs\pythonProject\lib\site-packages\sklearn\model_selection\_validation.py", line 593, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Josef\anaconda3\envs\pythonProject\lib\site-packages\skorch\net.py", line 917, in fit
    self.partial_fit(X, y, **fit_params)
  File "C:\Users\Josef\anaconda3\envs\pythonProject\lib\site-packages\skorch\net.py", line 876, in partial_fit
    self.fit_loop(X, y, **fit_params)
  File "C:\Users\Josef\anaconda3\envs\pythonProject\lib\site-packages\skorch\net.py", line 796, in fit_loop
    self.notify("on_epoch_end", **on_epoch_kwargs)
  File "C:\Users\Josef\anaconda3\envs\pythonProject\lib\site-packages\skorch\net.py", line 334, in notify
    getattr(cb, method_name)(self, **cb_kwargs)
  File "C:\Users\Josef\anaconda3\envs\pythonProject\lib\site-packages\skorch\callbacks\training.py", line 377, in on_epoch_end
    current_score = net.history[-1, self.monitor]
  File "C:\Users\Josef\anaconda3\envs\pythonProject\lib\site-packages\skorch\history.py", line 310, in __getitem__
    raise KeyError(keyerror_msg.format(k_e))
KeyError: "Key 'valid_loss' was not found in history."

  warnings.warn("Estimator fit failed. The score on this train-test"
[CV 2/2; 1/1] END batch_size=2, lr=1e-06, max_epochs=750, module__dropout=0.1; total time=   1.4s
C:\Users\Josef\anaconda3\envs\pythonProject\lib\site-packages\sklearn\model_selection\_search.py:918: UserWarning: One or more of the test scores are non-finite: [nan]
  warnings.warn(
Traceback (most recent call last):
  File "C:\Users\Josef\PycharmProjects\GANs\GANFromScratch_Hyperparameters.py", line 212, in <module>
    train_discriminator(real_data, fake_data)
  File "C:\Users\Josef\PycharmProjects\GANs\GANFromScratch_Hyperparameters.py", line 177, in train_discriminator
    train_discriminator.fit(real_data, ones)
  File "C:\Users\Josef\anaconda3\envs\pythonProject\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "C:\Users\Josef\anaconda3\envs\pythonProject\lib\site-packages\sklearn\model_selection\_search.py", line 880, in fit
    self.best_estimator_.fit(X, y, **fit_params)
  File "C:\Users\Josef\anaconda3\envs\pythonProject\lib\site-packages\skorch\net.py", line 917, in fit
    self.partial_fit(X, y, **fit_params)
  File "C:\Users\Josef\anaconda3\envs\pythonProject\lib\site-packages\skorch\net.py", line 876, in partial_fit
    self.fit_loop(X, y, **fit_params)
  File "C:\Users\Josef\anaconda3\envs\pythonProject\lib\site-packages\skorch\net.py", line 796, in fit_loop
    self.notify("on_epoch_end", **on_epoch_kwargs)
  File "C:\Users\Josef\anaconda3\envs\pythonProject\lib\site-packages\skorch\net.py", line 334, in notify
    getattr(cb, method_name)(self, **cb_kwargs)
  File "C:\Users\Josef\anaconda3\envs\pythonProject\lib\site-packages\skorch\callbacks\training.py", line 377, in on_epoch_end
    current_score = net.history[-1, self.monitor]
  File "C:\Users\Josef\anaconda3\envs\pythonProject\lib\site-packages\skorch\history.py", line 310, in __getitem__
    raise KeyError(keyerror_msg.format(k_e))
KeyError: "Key 'valid_loss' was not found in history."
```
with the following code:
```
from torch import nn, optim
from torchvision import transforms, datasets
import torch
from skorch import NeuralNet
from skorch import callbacks
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import GridSearchCV


DATA_FOLDER = './torch_data/VGAN/MNIST'


def mnist_data():
    compose = transforms.Compose([
        transforms.ToTensor(), transforms.Normalize([0.5], [0.5])])
    out_dir = 'C:\\Users\\Josef\\PycharmProjects\\GANs\\dataset'
    return datasets.MNIST(root=out_dir, train=True, transform=compose, download=False)
# Load data
data = mnist_data()
# Create loader with data, so that we can iterate over it
data_loader = torch.utils.data.DataLoader(data, batch_size=2, shuffle=False)
# Num batches
num_batches = len(data_loader)


def images_to_vectors(images):
    return images.view(images.size(0), 784)

def vectors_to_images(vectors):
    return vectors.view(vectors.size(0), 1, 28, 28)


class DiscriminatorNet(torch.nn.Module):
    """
    A three hidden-layer discriminative neural network
    """

    def __init__(self, dropout=.5):
        super(DiscriminatorNet, self).__init__()
        n_features = 784
        n_out = 1

        self.hidden0 = nn.Sequential(
            nn.Linear(n_features, 1024),
            nn.LeakyReLU(0.2),
            nn.Dropout(0.3)
        )
        self.hidden1 = nn.Sequential(
            nn.Linear(1024, 512),
            nn.LeakyReLU(0.2),
            nn.Dropout(0.3)
        )
        self.hidden2 = nn.Sequential(
            nn.Linear(512, 256),
            nn.LeakyReLU(0.2),
            nn.Dropout(0.3)
        )
        self.out = nn.Sequential(
            torch.nn.Linear(256, n_out),
            torch.nn.Sigmoid()
        )

    def forward(self, x):
        x = self.hidden0(x)
        x = self.hidden1(x)
        x = self.hidden2(x)
        x = self.out(x)
        return x

discriminator = DiscriminatorNet()
discriminator.to("cuda:0")

discriminator = NeuralNet(
    module=DiscriminatorNet,
    callbacks=[callbacks.EarlyStopping(patience=10)],
    criterion=torch.nn.MSELoss,
    optimizer=torch.optim.SGD,
    max_epochs=0,
    lr=0.00001,
    batch_size=2,
    iterator_train__shuffle=False,
    verbose=0,
    device="cuda:0",
    train_split=None)



class GeneratorNet(torch.nn.Module):
    """
    A three hidden-layer generative neural network
    """

    def __init__(self, dropout=.5):
        super(GeneratorNet, self).__init__()
        n_features = 100
        n_out = 784

        self.hidden0 = nn.Sequential(
            nn.Linear(n_features, 256),
            nn.LeakyReLU(0.2)
        )
        self.hidden1 = nn.Sequential(
            nn.Linear(256, 512),
            nn.LeakyReLU(0.2)
        )
        self.hidden2 = nn.Sequential(
            nn.Linear(512, 1024),
            nn.LeakyReLU(0.2)
        )

        self.out = nn.Sequential(
            nn.Linear(1024, n_out),
            nn.Tanh()
        )

    def forward(self, x):
        x = self.hidden0(x)
        x = self.hidden1(x)
        x = self.hidden2(x)
        x = self.out(x)
        return x

generator = GeneratorNet()
generator.to("cuda:0")

generator = NeuralNet(
    module=GeneratorNet,
    callbacks=[callbacks.EarlyStopping(patience=10)],
    criterion=torch.nn.MSELoss,
    optimizer=torch.optim.SGD,
    max_epochs=0,
    lr=0.00001,
    batch_size=2,
    iterator_train__shuffle=False,
    verbose=0,
    device="cuda:0",
    train_split=None)


def noise(size):
    '''
    Generates a 1-d vector of gaussian sampled random values
    '''
    n = torch.randn(size, 100, device='cuda:0')
    return n


def ones_target(size):
    '''
    Tensor containing ones, with shape = size
    '''
    data = torch.ones(size, 1)
    data = data.to("cuda:0")
    return data

def zeros_target(size):
    '''
    Tensor containing zeros, with shape = size
    '''
    data = torch.zeros(size, 1)
    data = data.to("cuda:0")
    return data


def train_discriminator(real_data, fake_data):
    params_discriminator = {
        'max_epochs': [750],
        'lr': [0.000001],
        'batch_size': [2],
        'module__dropout': [.1]}

    # 1.1 Train on Real Data
    train_discriminator = GridSearchCV(discriminator, params_discriminator, cv=2, scoring="neg_mean_squared_error",
                                         verbose=100,
                                         n_jobs=-1)
    ones = ones_target(N)
    train_discriminator.fit(real_data, ones)

    # 1.2 Train on Fake Data
    train_discriminator = GridSearchCV(discriminator, params_discriminator, cv=2,
                                             scoring="neg_mean_squared_error",
                                             verbose=100,
                                             n_jobs=-1)
    train_discriminator.fit(fake_data, zeros_target(N))


def train_generator(fake_data):
    params_generator = {
        'max_epochs': [750],
        'lr': [0.000001],
        'batch_size': [2],
        'module__dropout': [.1]}

    train_generator = GridSearchCV(generator, params_generator, cv=2, scoring="neg_mean_squared_error", verbose=100,
                                         n_jobs=-1)

    train_generator.fit(fake_data, ones_target(N))


# Total number of epochs to train
num_epochs = 200
for epoch in range(num_epochs):
    for real_batch, _ in data_loader:
        real_batch = real_batch.to('cuda:0')
        N = real_batch.size(0)
        # 1. Train Discriminator
        real_data = images_to_vectors(real_batch)
        # Generate fake data and detach (so gradients are not calculated for generator)
        generator.initialize()
        fake_data = generator.forward(noise(N)).detach()
        # Train D
        train_discriminator(real_data, fake_data)

        # 2. Train Generator
        # Generate fake data
        fake_data = generator.forward(noise(N))
        # Train generator
        train_generator(fake_data)
```
My thought is that somehow no validation data is provided but I guessed that I automatically provide validation data by the cross validation with GridSearchCV, don't I?

**Comment by BenjaminBossan** [comment]
Indeed, the reason for the error is that you set `train_split=None`. Usually, skorch will just ignore the missing validation data, but in your case, you're using `EarlyStopping`, which requires it. So either you have to remove `EarlyStopping`, make it monitor something else (but there is only really train loss), or add back validation data.

> but I guessed that I automatically provide validation data by the cross validation with GridSearchCV, don't I?

No, the validation data split off by sklearn is not available to the net. First for technical reasons, but also it wouldn't be desired: If the net gets to see the validation data, even if only for early stopping, it could overfit on the validation data. Therefore, if early stopping is required, part of the training data needs to be split off, which is what `train_split` is designed to do.

**Comment by Zepp3** [comment]
Hi @BenjaminBossan,
thank you, it worked!
