### ISSUE TITLE
Grid search error:  ValueError: Found array with dim 3. Estimator expected <= 2.

### ISSUE THREAD

**Issue by xiaolongwu0713** [skorch-dev/skorch#768]
Hi, I am running grid search on numpy array because I have some trouble with dataset. However I have below error msg:

```
Fitting 2 folds for each of 4 candidates, totalling 8 fits
[CV] lr=0.001, module__num_S=2 .......................................
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
On Epoch begin 1.
on batch end callback
on batch end callback
On Epoch begin 2.
on batch end callback
on batch end callback
Traceback (most recent call last):
  File "/Users/long/Documents/BCI/python_scripts/googleDrive/grasp/TSception/skorch_main.py", line 138, in <module>
    gs.fit(train_and_val_final_x,train_and_val_final_y)
  File "/usr/local/venv/3.6.9/lib/python3.6/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/usr/local/venv/3.6.9/lib/python3.6/site-packages/sklearn/model_selection/_search.py", line 736, in fit
    self._run_search(evaluate_candidates)
  File "/usr/local/venv/3.6.9/lib/python3.6/site-packages/sklearn/model_selection/_search.py", line 1188, in _run_search
    evaluate_candidates(ParameterGrid(self.param_grid))
  File "/usr/local/venv/3.6.9/lib/python3.6/site-packages/sklearn/model_selection/_search.py", line 715, in evaluate_candidates
    cv.split(X, y, groups)))
  File "/usr/local/venv/3.6.9/lib/python3.6/site-packages/joblib/parallel.py", line 1041, in __call__
    if self.dispatch_one_batch(iterator):
  File "/usr/local/venv/3.6.9/lib/python3.6/site-packages/joblib/parallel.py", line 859, in dispatch_one_batch
    self._dispatch(tasks)
  File "/usr/local/venv/3.6.9/lib/python3.6/site-packages/joblib/parallel.py", line 777, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/usr/local/venv/3.6.9/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/usr/local/venv/3.6.9/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/usr/local/venv/3.6.9/lib/python3.6/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/usr/local/venv/3.6.9/lib/python3.6/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "/usr/local/venv/3.6.9/lib/python3.6/site-packages/sklearn/model_selection/_validation.py", line 560, in _fit_and_score
    test_scores = _score(estimator, X_test, y_test, scorer)
  File "/usr/local/venv/3.6.9/lib/python3.6/site-packages/sklearn/model_selection/_validation.py", line 607, in _score
    scores = scorer(estimator, X_test, y_test)
  File "/usr/local/venv/3.6.9/lib/python3.6/site-packages/sklearn/metrics/_scorer.py", line 88, in __call__
    *args, **kwargs)
  File "/usr/local/venv/3.6.9/lib/python3.6/site-packages/sklearn/metrics/_scorer.py", line 213, in _score
    **self._kwargs)
  File "/usr/local/venv/3.6.9/lib/python3.6/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/usr/local/venv/3.6.9/lib/python3.6/site-packages/sklearn/metrics/_regression.py", line 256, in mean_squared_error
    y_true, y_pred, multioutput)
  File "/usr/local/venv/3.6.9/lib/python3.6/site-packages/sklearn/metrics/_regression.py", line 85, in _check_reg_targets
    y_true = check_array(y_true, ensure_2d=False, dtype=dtype)
  File "/usr/local/venv/3.6.9/lib/python3.6/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/usr/local/venv/3.6.9/lib/python3.6/site-packages/sklearn/utils/validation.py", line 641, in check_array
    % (array.ndim, estimator_name))
ValueError: Found array with dim 3. Estimator expected <= 2.
```
This is my code:

```
train_and_val_final_x=np.stack( train_and_val_wind_x).astype(np.float32) # (10, 280, 1, 90, 1000)
train_and_val_final_y=np.stack( train_and_val_wind_y).astype(np.float32) # (10, 280, 1)

from skorch.callbacks import Checkpoint, TrainEndCheckpoint, EarlyStopping
cp = Checkpoint(dirname=result_dir) # Will automatically save the model when there is an improvement during validation.
train_end_cp = TrainEndCheckpoint(dirname=result_dir) # save model and the end of the training

early_stopping_callbacks = EarlyStopping(monitor='valid_loss', lower_is_better=True, patience=5)

net = MyRegressor(
    module=TSception2,
    module__wind_size=T,
    module__step=step,
    module__sampling_rate=sampling_rate,
    module__chnNum=chnNum,
    module__num_T=num_ST,
    module__num_S=num_ST,
    module__batch_size=batch_size,
    module__dropout=dropout,
    lambda1=Lambda, # can be at at sequence location.
    iterator_train__shuffle=True,
    #train_split=predefined_split(val_ds), #disable this when do grid search
    train_split=None, # grid search
    verbose=0, # grid search
    max_epochs=2,
    lr=learning_rate,
    batch_size=1,
    optimizer=torch.optim.Adam,
    criterion = nn.MSELoss,
    callbacks=[('on_epoch_begin_callback', on_epoch_begin_callback),
               ('on_batch_end_callback',on_batch_end_callback),],
               #cp,train_end_cp], # early_stopping_callbacks
    device = device
)

params = {
    'lr': [0.001, 0.003],
    'module__num_S':[2,3],
    #'lambda1':[1e-6,1e-5],
    #'module__num_T':[2,3,4,5,6],
    #'module__dropout':[0.1,0.3,0.5,0.7],
    #'optimizer': [torch.optim.Adam, torch.optim.Adagrad ,torch.optim.SGD],
    #'optimizer__weight_decay':[0, 1e-04, 1e-03],
    #'max_epochs': [100,200, 300],
    #'module__num_units': [10, 20],
}

#net.fit(train_and_val_ds,y=None)
from sklearn.model_selection import GridSearchCV
gs = GridSearchCV(net, params, refit=False, cv=2, scoring='neg_mean_squared_error', verbose=2) # score: higher is better
gs.fit(train_and_val_final_x,train_and_val_final_y)

```
train_and_val_final_x.shape: (10, 280, 1, 90, 1000)
train_and_val_final_y.shape: (10, 280, 1)

Could you please advise？

**Comment by BenjaminBossan** [comment]
Numpy expects the `X` to be a 2d array, which your `X` is not. Since you're probably talking of the same problem as in #766, `SliceDataset` is probably still the best solution.

**Comment by xiaolongwu0713** [comment]
Does it means that if my input X is above 2 dimension then Numpy is not an option? And I have to go to SliceDataset?

**Comment by BenjaminBossan** [comment]
skorch itself doesn't care about how many dimensions `X` has but from the error message you posted above, it seems like sklearn doesn't like it. So either you need to use `SliceDataset` or you could try to monkey patch sklearn.

**Comment by BenjaminBossan** [comment]
I haven't heard back for some time, so I assume this is resolved. If not, feel free to re-open.
