### ISSUE TITLE
TensorBoard Callback and GridSearchCV

### ISSUE THREAD

**Issue by B1T0** [skorch-dev/skorch#818]
Hi,

I've tried to use the TensorBoard callback inside a `GridSearchCV` training loop but always get an error like at the end of this post. After finding nothing about it, I've seen that in your [example notebook](https://nbviewer.org/github/skorch-dev/skorch/blob/master/notebooks/MNIST-torchvision.ipynb) you tell users to turn the callback off for the grid search. 

Is using the TensorBoard callback in combination with `GridSearchCV` currently not supported? Otherwise, I would like to give more information on my environment and code to help to find the problem.

```
Traceback (most recent call last):
  File "/Volumes/Extreme SSD/mythesis/src/run_simplistic.py", line 139, in <module>
    sys.exit(main())
  File "/Volumes/Extreme SSD/mythesis/src/run_simplistic.py", line 110, in main
    grid.fit(
  File "/usr/local/Caskroom/miniconda/base/envs/mythesis/lib/python3.9/site-packages/sklearn/model_selection/_search.py", line 805, in fit
    base_estimator = clone(self.estimator)
  File "/usr/local/Caskroom/miniconda/base/envs/mythesis/lib/python3.9/site-packages/sklearn/base.py", line 81, in clone
    new_object_params[name] = clone(param, safe=False)
  File "/usr/local/Caskroom/miniconda/base/envs/mythesis/lib/python3.9/site-packages/sklearn/base.py", line 59, in clone
    return estimator_type([clone(e, safe=safe) for e in estimator])
  File "/usr/local/Caskroom/miniconda/base/envs/mythesis/lib/python3.9/site-packages/sklearn/base.py", line 59, in <listcomp>
    return estimator_type([clone(e, safe=safe) for e in estimator])
  File "/usr/local/Caskroom/miniconda/base/envs/mythesis/lib/python3.9/site-packages/sklearn/base.py", line 59, in clone
    return estimator_type([clone(e, safe=safe) for e in estimator])
  File "/usr/local/Caskroom/miniconda/base/envs/mythesis/lib/python3.9/site-packages/sklearn/base.py", line 59, in <listcomp>
    return estimator_type([clone(e, safe=safe) for e in estimator])
  File "/usr/local/Caskroom/miniconda/base/envs/mythesis/lib/python3.9/site-packages/sklearn/base.py", line 81, in clone
    new_object_params[name] = clone(param, safe=False)
  File "/usr/local/Caskroom/miniconda/base/envs/mythesis/lib/python3.9/site-packages/sklearn/base.py", line 59, in clone
    return estimator_type([clone(e, safe=safe) for e in estimator])
  File "/usr/local/Caskroom/miniconda/base/envs/mythesis/lib/python3.9/site-packages/sklearn/base.py", line 59, in <listcomp>
    return estimator_type([clone(e, safe=safe) for e in estimator])
  File "/usr/local/Caskroom/miniconda/base/envs/mythesis/lib/python3.9/site-packages/sklearn/base.py", line 59, in clone
    return estimator_type([clone(e, safe=safe) for e in estimator])
  File "/usr/local/Caskroom/miniconda/base/envs/mythesis/lib/python3.9/site-packages/sklearn/base.py", line 59, in <listcomp>
    return estimator_type([clone(e, safe=safe) for e in estimator])
  File "/usr/local/Caskroom/miniconda/base/envs/mythesis/lib/python3.9/site-packages/sklearn/base.py", line 81, in clone
    new_object_params[name] = clone(param, safe=False)
  File "/usr/local/Caskroom/miniconda/base/envs/mythesis/lib/python3.9/site-packages/sklearn/base.py", line 62, in clone
    return copy.deepcopy(estimator)
  File "/usr/local/Caskroom/miniconda/base/envs/mythesis/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/Caskroom/miniconda/base/envs/mythesis/lib/python3.9/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/Caskroom/miniconda/base/envs/mythesis/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Caskroom/miniconda/base/envs/mythesis/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Caskroom/miniconda/base/envs/mythesis/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/Caskroom/miniconda/base/envs/mythesis/lib/python3.9/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/Caskroom/miniconda/base/envs/mythesis/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Caskroom/miniconda/base/envs/mythesis/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Caskroom/miniconda/base/envs/mythesis/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/Caskroom/miniconda/base/envs/mythesis/lib/python3.9/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/Caskroom/miniconda/base/envs/mythesis/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Caskroom/miniconda/base/envs/mythesis/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Caskroom/miniconda/base/envs/mythesis/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/Caskroom/miniconda/base/envs/mythesis/lib/python3.9/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/Caskroom/miniconda/base/envs/mythesis/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Caskroom/miniconda/base/envs/mythesis/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Caskroom/miniconda/base/envs/mythesis/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/Caskroom/miniconda/base/envs/mythesis/lib/python3.9/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/Caskroom/miniconda/base/envs/mythesis/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Caskroom/miniconda/base/envs/mythesis/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Caskroom/miniconda/base/envs/mythesis/lib/python3.9/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle '_thread.lock' object
```

**Comment by BenjaminBossan** [comment]
When running grid search, sklearn tries to create a fresh copy of the initial model for each iteration. With tensorboard, this fails for some reason. Therefore, you cannot use tensorboard in conjunction with grid search and there is unfortunately not much that we can do about on the skorch side.

**Comment by B1T0** [comment]
Thank you for your fast response! 

I now tried a different route to use TensorBoard, and it worked so far: In one callback, I write all the information needed into the history. Then, in another callback, I can create the `SummaryWriter` inside the `on_train_end` method.

**Comment by BenjaminBossan** [comment]
Interesting, do you create a new instance of the summary writer each time or use a reference to the same one?

**Comment by B1T0** [comment]
I create a new summary writer for each trained model. So for each tested hyperparameter configuration, I create multiple summaries for the cross validation. 

The way I am currently using it seems to work, but TensorBoard is pretty much overwhelmed on my machine, so I guess there are better options if one needs to carefully inspect the results. However, as I wanted to use it in a rather quick-and-dirty manner, I got everything I required.

**Comment by BenjaminBossan** [comment]
> I create a new summary writer for each trained model. So for each tested hyperparameter configuration, I create multiple summaries for the cross validation.

This explains why it works, the same instance doesn't need to be cloned across processes.

> The way I am currently using it seems to work, but TensorBoard is pretty much overwhelmed on my machine, so I guess there are better options if one needs to carefully inspect the results. However, as I wanted to use it in a rather quick-and-dirty manner, I got everything I required.

It depends a bit on what you want out of the metrics. E.g. you can increase the verbosity (`GridSearchCV(..., verbose=3))` and it will report back the metrics after each iteration. If that's enough for you, you may not need tensorboard.
